        ,
        { "remove_asset", "media", "Delete a bin row",
          "Remove an asset from the media bin. Clips using it are not deleted.",
          objectSchema({{QStringLiteral("asset"), stringProp(QStringLiteral("Asset id or bin index"))}},
                       {QStringLiteral("asset")}),
          false, true },
        { "replace_asset", "media", "Swap source file",
          "Replace asset media from a local path or file URL.",
          objectSchema({{QStringLiteral("asset"), stringProp(QStringLiteral("Asset id or bin index"))},
                        {QStringLiteral("path"), stringProp(QStringLiteral("Absolute path or file:// URL"))}},
                       {QStringLiteral("asset"), QStringLiteral("path")}) },
        { "export_asset_image", "media", "Export a still from an asset",
          "Write an image file from a bin asset.",
          objectSchema({{QStringLiteral("asset"), stringProp(QStringLiteral("Asset id or bin index"))},
                        {QStringLiteral("path"), stringProp(QStringLiteral("Absolute output path"))}},
                       {QStringLiteral("asset"), QStringLiteral("path")}) },
        { "import_media_bytes", "media", "Import from base64",
          "Write bytes to disk then import. Provide path or name for the temp file.",
          objectSchema({{QStringLiteral("data"), stringProp(QStringLiteral("Base64-encoded file bytes"))},
                        {QStringLiteral("name"), stringProp(QStringLiteral("Filename hint (e.g. clip.mp4)"))},
                        {QStringLiteral("path"), stringProp(QStringLiteral("Optional absolute write path"))}},
                       {QStringLiteral("data"), QStringLiteral("name")}) },

        { "load_project", "project", "Open a .dcut project",
          "Load a project file. Replaces the open timeline.",
          objectSchema({{QStringLiteral("path"), stringProp(QStringLiteral("Absolute .dcut path"))}},
                       {QStringLiteral("path")}) },
        { "new_project", "project", "Start empty",
          "Discard the current timeline and create a new project.",
          objectSchema({}) },
        { "package_project", "project", "Save bundled copy",
          "Package project with embedded assets. Async — poll package progress in inspect if exposed.",
          objectSchema({{QStringLiteral("path"), stringProp(QStringLiteral("Absolute output .dcut path"))}},
                       {QStringLiteral("path")}) },
        { "cancel_package", "project", "Stop packaging",
          "Cancel an in-flight package job.",
          objectSchema({}) },
        { "cancel_export", "project", "Stop encoding",
          "Cancel an in-flight export.",
          objectSchema({}) },
        { "apply_canvas_crop", "project", "Crop canvas",
          "Crop the project canvas to a pixel rectangle.",
          objectSchema({{QStringLiteral("x"), numberProp(QStringLiteral("Left pixels"))},
                        {QStringLiteral("y"), numberProp(QStringLiteral("Top pixels"))},
                        {QStringLiteral("width"), numberProp(QStringLiteral("Width pixels"))},
                        {QStringLiteral("height"), numberProp(QStringLiteral("Height pixels"))}},
                       {QStringLiteral("x"), QStringLiteral("y"), QStringLiteral("width"), QStringLiteral("height")}) },

        { "move_track", "timeline", "Reorder lanes",
          "Move a track from one index to another.",
          objectSchema({{QStringLiteral("from"), integerProp(QStringLiteral("Source track index"))},
                        {QStringLiteral("to"), integerProp(QStringLiteral("Destination track index"))}},
                       {QStringLiteral("from"), QStringLiteral("to")}) },
        { "set_track_waveform", "timeline", "Show/hide waveform",
          "Toggle waveform display on an audio/video track row.",
          objectSchema({{QStringLiteral("track"), integerProp(QStringLiteral("Track index"))},
                        {QStringLiteral("show"), boolProp(QStringLiteral("Show waveform"))}},
                       {QStringLiteral("track"), QStringLiteral("show")}) },
        { "set_track_height", "timeline", "Resize a lane",
          "Set track height scale (0.6–4.0).",
          objectSchema({{QStringLiteral("track"), integerProp(QStringLiteral("Track index"))},
                        {QStringLiteral("scale"), numberProp(QStringLiteral("Height multiplier"))}},
                       {QStringLiteral("track"), QStringLiteral("scale")}) },
        { "select_clip", "timeline", "Focus one clip",
          "Select a single clip for merge/separate/unlink/align ops.",
          objectSchema(clipRefProps()) },
        { "clear_selection", "timeline", "Deselect all",
          "Clear the clip selection.",
          objectSchema({}) },
        { "select_all_clips", "timeline", "Select everything",
          "Select all clips on the timeline.",
          objectSchema({}) },
        { "copy_selection", "timeline", "Copy to clipboard",
          "Copy selected clips.",
          objectSchema({}) },
        { "cut_selection", "timeline", "Cut to clipboard",
          "Cut selected clips.",
          objectSchema({}) },
        { "paste_at_playhead", "timeline", "Paste clips",
          "Paste clipboard clips at the playhead.",
          objectSchema({}) },
        { "separate_audio", "timeline", "Split A/V",
          "Separate audio from the selected video clip.",
          objectSchema({}) },
        { "unlink_audio", "timeline", "Break A/V link",
          "Unlink linked audio/video clips in the selection.",
          objectSchema({}) },
        { "merge_clips", "timeline", "Join adjacent clips",
          "Merge selected adjacent clips on the same track.",
          objectSchema({}) },
        { "align_clip_left", "timeline", "Snap start to zero",
          "Align selected clip to timeline start.",
          objectSchema({}) },
        { "align_clip_right", "timeline", "Snap end to duration",
          "Align selected clip end to project duration.",
          objectSchema({}) },
        { "set_clip_name", "timeline", "Rename a clip",
          "Set the clip display name.",
          objectSchema(mergeProps({{QStringLiteral("name"), stringProp(QStringLiteral("New name"))}},
                                  clipRefProps()),
                       {QStringLiteral("name")}) },
        { "add_bookmark", "timeline", "Mark a time",
          "Add a bookmark at seconds with optional label.",
          objectSchema({{QStringLiteral("at"), numberProp(QStringLiteral("Seconds"))},
                        {QStringLiteral("label"), stringProp(QStringLiteral("Label"))}},
                       {QStringLiteral("at")}) },
        { "remove_bookmark", "timeline", "Delete bookmark",
          "Remove bookmark by index.",
          objectSchema({{QStringLiteral("index"), integerProp(QStringLiteral("Bookmark index"))}},
                       {QStringLiteral("index")}),
          false, true },
        { "update_bookmark", "timeline", "Edit bookmark",
          "Update bookmark time and label.",
          objectSchema({{QStringLiteral("index"), integerProp(QStringLiteral("Bookmark index"))},
                        {QStringLiteral("at"), numberProp(QStringLiteral("Seconds"))},
                        {QStringLiteral("label"), stringProp(QStringLiteral("Label"))}},
                       {QStringLiteral("index")}) },
        { "go_to_bookmark", "timeline", "Seek to bookmark",
          "Seek playhead to bookmark index.",
          objectSchema({{QStringLiteral("index"), integerProp(QStringLiteral("Bookmark index"))}},
                       {QStringLiteral("index")}) },
        { "freeze_frame", "timeline", "Hold current frame",
          "Insert a freeze frame at the playhead.",
          objectSchema({}) },

        { "set_flip", "canvas", "Mirror a clip",
          "Set horizontal and/or vertical flip.",
          objectSchema(mergeProps({{QStringLiteral("flipH"), boolProp(QStringLiteral("Flip horizontally"))},
                                   {QStringLiteral("flipV"), boolProp(QStringLiteral("Flip vertically"))}},
                                  clipRefProps())) },
        { "set_blend_mode", "canvas", "Change compositing",
          "Set clip blend mode (normal, multiply, screen, …).",
          objectSchema(mergeProps({{QStringLiteral("mode"), stringProp(QStringLiteral("Blend mode id"))}},
                                  clipRefProps()),
                       {QStringLiteral("mode")}) },
        { "set_mask", "canvas", "Clip mask",
          "Patch clip mask settings.",
          objectSchema(mergeProps({{QStringLiteral("mask"), objectSchema({})}},
                                  clipRefProps())) },
        { "set_fade", "canvas", "Audio/video fade",
          "Set fade-in and fade-out seconds.",
          objectSchema(mergeProps({{QStringLiteral("in"), numberProp(QStringLiteral("Fade in seconds"))},
                                   {QStringLiteral("out"), numberProp(QStringLiteral("Fade out seconds"))}},
                                  clipRefProps())) },
        { "set_fade_curve", "canvas", "Fade curve preset",
          "Set fade curve kind (linear, ease, …).",
          objectSchema(mergeProps({{QStringLiteral("curve"), stringProp(QStringLiteral("Curve id"))}},
                                  clipRefProps()),
                       {QStringLiteral("curve")}) },
        { "set_clip_speed", "canvas", "Constant speed",
          "Set scalar playback speed (not a ramp). Clears speed curve if present.",
          objectSchema(mergeProps({{QStringLiteral("speed"), numberProp(QStringLiteral("Playback rate"))}},
                                  clipRefProps()),
                       {QStringLiteral("speed")}) },
        { "set_clip_reverse", "canvas", "Reverse playback",
          "Reverse clip playback. May start proxy render for video.",
          objectSchema(mergeProps({{QStringLiteral("reverse"), boolProp(QStringLiteral("Reversed"))}},
                                  clipRefProps()),
                       {QStringLiteral("reverse")}) },
        { "cancel_reverse_render", "canvas", "Stop reverse proxy",
          "Cancel in-flight reverse proxy render.",
          objectSchema({}) },
        { "set_animation", "canvas", "In/out motion",
          "Patch animIn or animOut ({kind, duration, ease, curve}).",
          objectSchema(mergeProps({{QStringLiteral("which"), enumProp(QStringLiteral("animIn or animOut"),
                                                                       {QStringLiteral("animIn"),
                                                                        QStringLiteral("animOut")})},
                                   {QStringLiteral("kind"), stringProp(QStringLiteral("Animation kind"))},
                                   {QStringLiteral("duration"), numberProp(QStringLiteral("Seconds"))},
                                   {QStringLiteral("ease"), stringProp(QStringLiteral("Ease id"))},
                                   {QStringLiteral("curve"), stringProp(QStringLiteral("Curve id"))}},
                                  clipRefProps()),
                       {QStringLiteral("which")}) },
        { "set_shape_style", "canvas", "Shape look",
          "Patch shape clip style (fill, stroke, …).",
          objectSchema(mergeProps({{QStringLiteral("style"), objectSchema({})}},
                                  clipRefProps())) },

        { "list_shapes", "shapes", "Builtin shapes",
          "Returns shape catalog entries.",
          objectSchema({}), true, false, true },
        { "list_stickers", "shapes", "Builtin stickers",
          "Returns sticker catalog entries.",
          objectSchema({}), true, false, true },
        { "list_emoji", "shapes", "Emoji catalog",
          "Returns emoji entries.",
          objectSchema({}), true, false, true },
        { "list_text_presets", "shapes", "Text style packs",
          "Returns text preset ids.",
          objectSchema({}), true, false, true },
        { "list_fonts", "shapes", "Font list",
          "Returns available fonts.",
          objectSchema({}), true, false, true },
        { "add_shape", "shapes", "Place a shape",
          "Add a builtin shape clip.",
          objectSchema({{QStringLiteral("shape"), stringProp(QStringLiteral("Shape id from list_shapes"))},
                        {QStringLiteral("at"), numberProp(QStringLiteral("Start seconds"))},
                        {QStringLiteral("track"), integerProp(QStringLiteral("Optional track"))}}) },
        { "add_sticker", "shapes", "Place a sticker",
          "Add a sticker clip.",
          objectSchema({{QStringLiteral("sticker"), stringProp(QStringLiteral("Sticker id"))},
                        {QStringLiteral("at"), numberProp(QStringLiteral("Start seconds"))}}) },
        { "add_emoji", "shapes", "Place emoji",
          "Add an emoji clip.",
          objectSchema({{QStringLiteral("emoji"), stringProp(QStringLiteral("Emoji character"))},
                        {QStringLiteral("name"), stringProp(QStringLiteral("Display name"))},
                        {QStringLiteral("at"), numberProp(QStringLiteral("Start seconds"))}}) },

        { "add_subtitle_clip", "subtitles", "Empty subtitle lane",
          "Add a subtitle clip at seconds.",
          objectSchema({{QStringLiteral("at"), numberProp(QStringLiteral("Start seconds"))}}) },
        { "import_subtitle_file", "subtitles", "Load SRT/VTT",
          "Import subtitles as a new clip at seconds.",
          objectSchema({{QStringLiteral("path"), stringProp(QStringLiteral("Absolute subtitle file path"))},
                        {QStringLiteral("at"), numberProp(QStringLiteral("Start seconds (default playhead)"))}},
                       {QStringLiteral("path")}) },
        { "import_subtitle_into_clip", "subtitles", "Load into clip",
          "Import subtitle file into an existing subtitle clip.",
          objectSchema(mergeProps({{QStringLiteral("path"), stringProp(QStringLiteral("Absolute path"))}},
                                  clipRefProps()),
                       {QStringLiteral("path")}) },
        { "export_subtitle_file", "subtitles", "Write subtitles",
          "Export subtitle cues to a file.",
          objectSchema(mergeProps({{QStringLiteral("path"), stringProp(QStringLiteral("Absolute output path"))}},
                                  clipRefProps()),
                       {QStringLiteral("path")}) },
        { "set_subtitle_cues", "subtitles", "Replace all cues",
          "Set cues [{start, end, text}, …] in seconds.",
          objectSchema(mergeProps(
              {{QStringLiteral("cues"),
                arrayProp(objectSchema({{QStringLiteral("start"), numberProp(QStringLiteral("Start sec"))},
                                        {QStringLiteral("end"), numberProp(QStringLiteral("End sec"))},
                                        {QStringLiteral("text"), stringProp(QStringLiteral("Caption"))}}),
                           QStringLiteral("Cue list"))}},
              clipRefProps()),
                       {QStringLiteral("cues")}) },
        { "upsert_subtitle_cue", "subtitles", "Edit cue at playhead",
          "Add or update cue text at the playhead.",
          objectSchema(mergeProps({{QStringLiteral("text"), stringProp(QStringLiteral("Caption text"))}},
                                  clipRefProps()),
                       {QStringLiteral("text")}) },
        { "list_whisper_languages", "subtitles", "Whisper languages",
          "Languages supported for auto-captioning.",
          objectSchema({}), true, false, true },
        { "generate_subtitles", "subtitles", "Auto transcribe",
          "Run Whisper on a clip. Async — poll subtitle generation state.",
          objectSchema(mergeProps({{QStringLiteral("language"), stringProp(QStringLiteral("Language code"))}},
                                  clipRefProps())) },
        { "cancel_subtitle_generation", "subtitles", "Stop Whisper",
          "Cancel in-flight subtitle generation.",
          objectSchema({}) },

        { "set_effect_enabled", "effects", "Toggle effect",
          "Enable or disable a video effect.",
          objectSchema(mergeProps({{QStringLiteral("index"), integerProp(QStringLiteral("Effect index"))},
                                   {QStringLiteral("enabled"), boolProp(QStringLiteral("Enabled"))}},
                                  clipRefProps()),
                       {QStringLiteral("index"), QStringLiteral("enabled")}) },
        { "move_effect", "effects", "Reorder effect",
          "Move effect from one stack index to another.",
          objectSchema(mergeProps({{QStringLiteral("from"), integerProp(QStringLiteral("From index"))},
                                   {QStringLiteral("to"), integerProp(QStringLiteral("To index"))}},
                                  clipRefProps()),
                       {QStringLiteral("from"), QStringLiteral("to")}) },
        { "set_effect_color_param", "effects", "Color effect param",
          "Set a color parameter (#RRGGBB or #AARRGGBB).",
          objectSchema(mergeProps({{QStringLiteral("index"), integerProp(QStringLiteral("Effect index"))},
                                   {QStringLiteral("key"), stringProp(QStringLiteral("Parameter key"))},
                                   {QStringLiteral("value"), stringProp(QStringLiteral("Color"))}},
                                  clipRefProps()),
                       {QStringLiteral("index"), QStringLiteral("key"), QStringLiteral("value")}) },
        { "set_audio_effect_enabled", "effects", "Toggle audio effect",
          "Enable or disable an audio effect.",
          objectSchema(mergeProps({{QStringLiteral("index"), integerProp(QStringLiteral("Effect index"))},
                                   {QStringLiteral("enabled"), boolProp(QStringLiteral("Enabled"))}},
                                  clipRefProps()),
                       {QStringLiteral("index"), QStringLiteral("enabled")}) },
        { "move_audio_effect", "effects", "Reorder audio effect",
          "Move audio effect between stack indices.",
          objectSchema(mergeProps({{QStringLiteral("from"), integerProp(QStringLiteral("From index"))},
                                   {QStringLiteral("to"), integerProp(QStringLiteral("To index"))}},
                                  clipRefProps()),
                       {QStringLiteral("from"), QStringLiteral("to")}) },
        { "list_effect_templates", "effects", "Effect packs",
          "Returns effect template catalog.",
          objectSchema({}), true, false, true },
        { "apply_effect_template", "effects", "Apply template",
          "Apply an effect template pack to a clip.",
          objectSchema(mergeProps({{QStringLiteral("template"), stringProp(QStringLiteral("Template id"))}},
                                  clipRefProps()),
                       {QStringLiteral("template")}) },
        { "set_transition_kind", "effects", "Change transition type",
          "Set transition kind by id on a track.",
          objectSchema({{QStringLiteral("track"), integerProp(QStringLiteral("Track index"))},
                        {QStringLiteral("id"), stringProp(QStringLiteral("Transition id"))},
                        {QStringLiteral("kind"), stringProp(QStringLiteral("Kind from list_transitions"))}},
                       {QStringLiteral("track"), QStringLiteral("id"), QStringLiteral("kind")}) },
        { "set_transition_duration", "effects", "Transition length",
          "Set transition duration in seconds.",
          objectSchema({{QStringLiteral("track"), integerProp(QStringLiteral("Track index"))},
                        {QStringLiteral("id"), stringProp(QStringLiteral("Transition id"))},
                        {QStringLiteral("duration"), numberProp(QStringLiteral("Seconds"))}},
                       {QStringLiteral("track"), QStringLiteral("id"), QStringLiteral("duration")}) },
        { "set_transition_param", "effects", "Transition param",
          "Set a numeric transition parameter.",
          objectSchema({{QStringLiteral("track"), integerProp(QStringLiteral("Track index"))},
                        {QStringLiteral("id"), stringProp(QStringLiteral("Transition id"))},
                        {QStringLiteral("key"), stringProp(QStringLiteral("Param key"))},
                        {QStringLiteral("value"), numberProp(QStringLiteral("Value"))}},
                       {QStringLiteral("track"), QStringLiteral("id"), QStringLiteral("key"),
                        QStringLiteral("value")}) },

        { "move_keyframe", "keyframes", "Move a key",
          "Move keyframe from one time to another (timeline seconds).",
          objectSchema(mergeProps({{QStringLiteral("prop"), stringProp(QStringLiteral("Property"))},
                                   {QStringLiteral("from"), numberProp(QStringLiteral("From seconds"))},
                                   {QStringLiteral("to"), numberProp(QStringLiteral("To seconds"))},
                                   {QStringLiteral("value"), numberProp(QStringLiteral("Optional new value"))}},
                                  clipRefProps()),
                       {QStringLiteral("prop"), QStringLiteral("from"), QStringLiteral("to")}) },

        { "list_fade_curve", "speed", "Read custom fade shape",
          "Returns fade curve points for a clip (opens transient session).",
          objectSchema(clipRefProps()), true, false, true },
        { "set_fade_curve", "speed", "Custom fade shape",
          "Set fade curve points and apply to clip.",
          objectSchema(mergeProps(
              {{QStringLiteral("points"),
                arrayProp(objectSchema({{QStringLiteral("t"), numberProp(QStringLiteral("Time 0..1"))},
                                        {QStringLiteral("g"), numberProp(QStringLiteral("Gain 0..1"))}}),
                           QStringLiteral("Curve points"))}},
              clipRefProps()),
                       {QStringLiteral("points")}) },

        { "segmentation_status", "segmentation", "Check availability",
          "Returns {available, model}.",
          objectSchema({}), true, false, true },
        { "begin_segmentation_session", "segmentation", "Open segment UI state",
          "Begin interactive segmentation on a frame.",
          objectSchema(mergeProps({{QStringLiteral("at"), numberProp(QStringLiteral("Frame seconds"))},
                                   {QStringLiteral("forTemplate"), boolProp(QStringLiteral("Template mode"))}},
                                  clipRefProps())) },
        { "end_segmentation_session", "segmentation", "Close session",
          "End segmentation session without applying.",
          objectSchema({}) },
        { "set_segmentation_frame", "segmentation", "Pick frame",
          "Seek segmentation preview to seconds.",
          objectSchema({{QStringLiteral("at"), numberProp(QStringLiteral("Seconds"))}},
                       {QStringLiteral("at")}) },
        { "add_segmentation_point", "segmentation", "Add SAM point",
          "Add include/exclude point in normalised 0..1 x/y.",
          objectSchema({{QStringLiteral("x"), numberProp(QStringLiteral("X 0..1"))},
                        {QStringLiteral("y"), numberProp(QStringLiteral("Y 0..1"))},
                        {QStringLiteral("include"), boolProp(QStringLiteral("Include region"))}},
                       {QStringLiteral("x"), QStringLiteral("y")}) },
        { "remove_segmentation_point", "segmentation", "Remove SAM point",
          "Remove point by index.",
          objectSchema({{QStringLiteral("index"), integerProp(QStringLiteral("Point index"))}},
                       {QStringLiteral("index")}) },
        { "clear_segmentation_points", "segmentation", "Clear points",
          "Remove all segmentation points.",
          objectSchema({}) },
        { "run_segmentation", "segmentation", "Run from session",
          "Run segmentation with current session points. output: clips or mask.",
          objectSchema({{QStringLiteral("output"), enumProp(QStringLiteral("Output mode"),
                                                             {QStringLiteral("clips"), QStringLiteral("mask")})}}) },
        { "segment_clip", "segmentation", "One-shot segment",
          "Segment with explicit points. output clips or mask.",
          objectSchema(mergeProps(
              {{QStringLiteral("points"),
                arrayProp(objectSchema({{QStringLiteral("x"), numberProp(QStringLiteral("X 0..1"))},
                                        {QStringLiteral("y"), numberProp(QStringLiteral("Y 0..1"))},
                                        {QStringLiteral("include"), boolProp(QStringLiteral("Include"))}}),
                           QStringLiteral("Points"))},
               {QStringLiteral("output"), stringProp(QStringLiteral("clips or mask"))}},
              clipRefProps()),
                       {QStringLiteral("points")}) },
        { "cancel_segmentation", "segmentation", "Stop segment job",
          "Cancel in-flight segmentation.",
          objectSchema({}) },

        { "denoise_status", "ai", "Denoise availability",
          "Returns whether denoise is available.",
          objectSchema({}), true, false, true },
        { "apply_denoise", "ai", "Denoise clip",
          "Apply denoise to clip at optional seconds.",
          objectSchema(mergeProps({{QStringLiteral("at"), numberProp(QStringLiteral("Preview seconds"))}},
                                  clipRefProps())) },
        { "cancel_denoise", "ai", "Cancel denoise",
          "Cancel in-flight denoise.",
          objectSchema({}) },
        { "face_detection_status", "ai", "Face track availability",
          "Returns whether face detection is available.",
          objectSchema({}), true, false, true },
        { "detect_faces", "ai", "Detect faces",
          "Run face detection on a clip. Async.",
          objectSchema(clipRefProps()) },
        { "cancel_face_detection", "ai", "Cancel face detect",
          "Cancel in-flight face detection.",
          objectSchema({}) },
        { "clear_face_track", "ai", "Remove face track",
          "Clear face track data from a clip.",
          objectSchema(clipRefProps()), false, true },

        { "set_ui_preferences", "ui", "Editor flags",
          "Set autoKey, mediaGrid, reopenLastProject, and/or followSystem theme.",
          objectSchema({{QStringLiteral("autoKey"), boolProp(QStringLiteral("Auto-keyframe"))},
                        {QStringLiteral("mediaGrid"), boolProp(QStringLiteral("Media grid mode"))},
                        {QStringLiteral("reopenLastProject"), boolProp(QStringLiteral("Reopen last on launch"))},
                        {QStringLiteral("followSystem"), boolProp(QStringLiteral("Follow OS theme"))}}) }
